"use strict";
let FavoritePlaces = ["Swat", "New York", "AJK", "Dubai", "Sydney"];
console.log("Original Order " + FavoritePlaces + "\n");
console.log("Alphabetical Order " + [...FavoritePlaces].sort() + "\n");
console.log("Original Order " + FavoritePlaces + "\n");
console.log("Reverse Alphabetical Order " + [...FavoritePlaces].sort().reverse() + "\n");
console.log("Original Order " + FavoritePlaces + "\n");
console.log("Reverse Order of list " + FavoritePlaces.reverse() + "\n");
console.log("Reverse Order of list " + FavoritePlaces.reverse() + "\n");
console.log("Alphabetical Order " + FavoritePlaces.sort() + "\n");
console.log("Alphabetical Order " + FavoritePlaces.sort().reverse() + "\n");
